version: '3.8'

services:
  backend:
    build:
      context: . # Specifies the build context, usually the current directory
      dockerfile: Dockerfile
    container_name: event-backend
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017/analyticsdb
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app
    command: sh -c "npm run build && node dist/main.js"

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  mongo-data:
